# Generated by Django 4.0.4 on 2022-08-26 03:18

import Display.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(choices=[('.tcx', '.tcx')], default='.tcx', max_length=30)),
                ('arquivo', models.FileField(upload_to=Display.models.user_dir)),
                ('ftp', models.FloatField(blank=True, null=True)),
                ('duracao_s', models.FloatField(blank=True, null=True)),
                ('NP', models.FloatField(blank=True, null=True)),
                ('IF', models.FloatField(blank=True, null=True)),
                ('PM', models.FloatField(blank=True, null=True)),
                ('TTS', models.FloatField(blank=True, null=True)),
                ('CM', models.FloatField(blank=True, null=True)),
                ('PMax', models.FloatField(blank=True, null=True)),
                ('PMin', models.FloatField(blank=True, null=True)),
                ('CMax', models.FloatField(blank=True, null=True)),
                ('CMin', models.FloatField(blank=True, null=True)),
                ('Calorias', models.FloatField(blank=True, null=True)),
                ('Distancia', models.FloatField(blank=True, null=True)),
                ('GraficoPot', models.CharField(blank=True, max_length=10000, null=True)),
                ('GraficoCad', models.CharField(blank=True, max_length=10000, null=True)),
                ('GraficoZonas', models.CharField(blank=True, max_length=10000, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treinos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
