# Generated by Django 4.0.4 on 2022-08-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0002_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='GraficoCad',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoPot',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoZonas',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
