# Generated by Django 4.0.4 on 2022-08-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0003_alter_treino_graficocad_alter_treino_graficopot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='GraficoCad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoPot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoZonas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
