# Generated by Django 4.0.4 on 2022-08-28 13:52

import Display.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0004_alter_treino_graficocad_alter_treino_graficopot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='GraficoCad',
            field=models.FileField(blank=True, null=True, upload_to=Display.models.user_dir),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoPot',
            field=models.FileField(blank=True, null=True, upload_to=Display.models.user_dir),
        ),
        migrations.AlterField(
            model_name='treino',
            name='GraficoZonas',
            field=models.FileField(blank=True, null=True, upload_to=Display.models.user_dir),
        ),
    ]
